trigger:
- master

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build Service Fabric Services
    pool:
      vmImage: 'windows-latest'
    steps:
      # Install nuget.exe
      - task: NuGetToolInstaller@1
        displayName: Install Nuget Tools
        inputs:
          versionSpec: '4.9.3'
          
      - task: PowerShell@2
        displayName: Build Application
        inputs:
          targetType: 'inline'
          script: |
            # Restore SF Build SDK
            nuget restore ./src/SFDemo/SFDemo/ -PackagesDirectory ./src/SFDemo/packages/

            # Publish SF Application
            dotnet build src/SFDemo/SFDemo/SFDemo.sfproj

            # Publish SF Service
            dotnet build src/SFDemo/SFDemo.sln

            cp ./src/SFDemo/* $(Build.ArtifactStagingDirectory)/ -R
      
      # Publish artifacts
      - task: PublishPipelineArtifact@0
        displayName: Publish Artifacts for Deployment
        inputs:
          artifactName: 'drop' 
          targetPath: $(Build.ArtifactStagingDirectory)